version: '3.3'
services:
  app:
      image: 'jc21/nginx-proxy-manager:latest'
      restart: unless-stopped
      ports:
        - '80:80'
        - '81:81'
        - '443:443'
      volumes:
        - ./data:/data
        - ./letsencrypt:/etc/letsencrypt
      networks:
        - mynetwork
  coodbox:
    image: coodbox-server:latest 
    environment:
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017}
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
   
    networks:
      - mynetwork
    # If your app is not running as root, you might need to add:
    # user: "1000:1000"  # Replace with the appropriate UID:GID

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  mongodb_data: