version: '3.8'
services:
  cobox:
    image: cobox-server:latest
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017}
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
    