database:
  name: cobox_db
  mongo_collection:
    submission: submission
    test_case: test_case
    account: account
    problem: problem
    submission_snippet: submission_snippet
token:
  expires_in: 24h
http:
  address: "0.0.0.0:8080"
logic:
  judge:
    schedule: "@every 5s"
    submission_retry_delay: 5s
    languages:
      - value: cpp
        name: C++
        test_case_run:
          image: "docker.io/library/debian:bullseye-slim"
          command_template:
            ["timeout", "--foreground", "$TIME_LIMIT", "$PROGRAM"]
          cpu_quota: 1000000
          code_file_name: main.cpp
          test_file_name: test.cpp
      - value: java
        name: Java
        test_case_run:
          image: "docker.io/library/openjdk:22-jdk-slim-buster"
          command_template: [
              "/bin/sh",
              "-c",
              "apt-get update && apt-get install -y wget &&
              wget https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.7.0/junit-platform-console-standalone-1.7.0.jar &&
              javac -cp junit-platform-console-standalone-1.7.0.jar Solution.java SolutionTest.java &&
              timeout --foreground $TIME_LIMIT java -jar junit-platform-console-standalone-1.7.0.jar --details verbose --reports-dir=reports --class-path . --select-class SolutionTest",
            ]
          cpu_quota: 1000000
          code_file_name: Solution.java
          test_file_name: SolutionTest.java
          stdErr: true
          stdOut: true
          download_test_url: https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.7.0/junit-platform-console-standalone-1.7.0.jar
          test_library_name: junit-platform-console-standalone-1.7.0.jar
      - value: python
        name: Python 3
        test_case_run:
          image: "docker.io/library/python:3.13-rc-slim"
          command_template:
            ["timeout", "--foreground", "$TIME_LIMIT", "python", "$TEST_FILE"]
          cpu_quota: 1000000
          code_file_name: main.py
          test_file_name: test.py
          stdErr: true
          stdOut: true
