database:
  file_path: cato_db
  mongo_collection:
    submission: submission
    test_case: test_case
    account: account
    problem: problem
    submission_snippet: submission_snippet
token:
  expires_in: 24h
http:
  address: "localhost:8080"
logic:
  judge:
    schedule: "@every 5s"
    submission_retry_delay: 5s
    languages:
      - value: cpp
        name: C++
        test_case_run:
          image: "docker.io/library/debian:bullseye-slim"
          command_template:
            ["timeout", "--foreground", "$TIME_LIMIT", "$PROGRAM"]
          cpu_quota: 1000000
          code_file_name: main.cpp
          test_file_name: test.cpp
      - value: java
        name: Java
        test_case_run:
          image: "docker.io/library/openjdk:22-jdk-slim-buster"
          command_template:
            ["timeout", "--foreground", "$TIME_LIMIT", "java", "Main"]
          cpu_quota: 1000000
          code_file_name: main.java
          test_file_name: test.java
      - value: python
        name: Python 3
        test_case_run:
          image: "docker.io/library/python:3.13-rc-slim"
          command_template:
            ["timeout", "--foreground", "$TIME_LIMIT", "python", "$TEST_FILE"]
          cpu_quota: 1000000
          code_file_name: main.py
          test_file_name: test.py
