# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Manual Deploy to VPS

on:
  workflow_dispatch:
    inputs:
      deploy_environment:
        description: "Environment to deploy to"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Build
        run: go build -v ./...

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /work/server
            echo "Deploying to server VPS"
            echo "Pulling latest changes..."
            git pull origin main
            echo "Building Docker image..."
            docker build -t coodbox-server:latest .
            echo "Restarting containers..."
            docker-compose down
            docker-compose up -d
            echo "Deployment complete!"
